version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: alten
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alten-ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5488:5432"
    networks:
      - alten-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - alten-network

volumes:
  postgres_data:

networks:
  alten-network:
    driver: bridge
